services: 
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - 5432:5432
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - .env
    ports: 
      - 8080:8080
    
  